<a href="https://colab.research.google.com/github/shahzarhusain/python_libraries/blob/main/pharma_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [113]:
import numpy as np
import pandas as pd

In [114]:
!gdown 173A59xh2mnpmljCCB9bhC4C5eP2IS6qZ

Downloading...
From: https://drive.google.com/uc?id=173A59xh2mnpmljCCB9bhC4C5eP2IS6qZ
To: /content/Pfizer_1.csv
100% 1.51k/1.51k [00:00<00:00, 4.23MB/s]

In [115]:
df = pd.read_csv('Pfizer_1.csv')

In [116]:
df.head()

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20

In [117]:
# melt is kind of anti pivoting, this will bring the col as category to each row
pd.melt(df, id_vars = ['Date', 'Drug_Name', 'Parameter']).sort_values(by = ['Date', 'Drug_Name', 'Parameter'])

           Date                Drug_Name    Parameter  variable  value
1    15-10-2020  diltiazem hydrochloride     Pressure   1:30:00   12.0
19   15-10-2020  diltiazem hydrochloride     Pressure   2:30:00   13.0
37   15-10-2020  diltiazem hydrochloride     Pressure   3:30:00    NaN
55   15-10-2020  diltiazem hydrochloride     Pressure   4:30:00   11.0
73   15-10-2020  diltiazem hydrochloride     Pressure   5:30:00   13.0
..          ...                      ...          ...       ...    ...
142  17-10-2020   ketamine hydrochloride  Temperature   8:30:00   20.0
160  17-10-2020   ketamine hydrochloride  Temperature   9:30:00   21.0
178  17-10-2020   ketamine hydrochloride  Temperature  10:30:00   22.0
196  17-10-2020   ketamine hydrochloride  Temperature  11:30:00   23.0
214  17-10-2020   ketamine hydrochloride  Temperature  12:30:00   24.0

[216 rows x 5 columns]

In [118]:
# let's save our melted data with proper names
melted_df = pd.melt(df, id_vars= ['Date','Drug_Name','Parameter'],
                    var_name = 'Time',
                    value_name= 'Readings')
melted_df.head()

         Date                Drug_Name    Parameter     Time  Readings
0  15-10-2020  diltiazem hydrochloride  Temperature  1:30:00      23.0
1  15-10-2020  diltiazem hydrochloride     Pressure  1:30:00      12.0
2  15-10-2020      docetaxel injection  Temperature  1:30:00       NaN
3  15-10-2020      docetaxel injection     Pressure  1:30:00       NaN
4  15-10-2020   ketamine hydrochloride  Temperature  1:30:00      24.0

In [119]:
# let's try to group our data
melted_df.groupby(['Date','Drug_Name','Parameter'])['Readings'].mean()

Date        Drug_Name                Parameter
15-10-2020  diltiazem hydrochloride  Pressure       16.000000
                                     Temperature    21.454545
            docetaxel injection      Pressure       24.875000
                                     Temperature    20.750000
            ketamine hydrochloride   Pressure        9.333333
                                     Temperature    23.555556
16-10-2020  diltiazem hydrochloride  Pressure       22.545455
                                     Temperature    37.454545
            docetaxel injection      Pressure       27.000000
                                     Temperature    51.454545
            ketamine hydrochloride   Pressure       14.800000
                                     Temperature    11.500000
17-10-2020  diltiazem hydrochloride  Pressure        7.727273
                                     Temperature    15.636364
            docetaxel injection      Pressure       24.500000
                                     Temperature    17.500000
            ketamine hydrochloride   Pressure       11.500000
                                     Temperature    18.500000
Name: Readings, dtype: float64

In [120]:
# now, just to practive the pivot, let's try to revert back to the melted data
melted_df.pivot(index = ['Date', 'Drug_Name', 'Parameter'],
                columns = 'Time',
                values = 'Readings')

Time                                            10:30:00  11:30:00  12:30:00  \
Date       Drug_Name               Parameter
15-10-2020 diltiazem hydrochloride Pressure         18.0      19.0      20.0
                                   Temperature      20.0      20.0      21.0
           docetaxel injection     Pressure         26.0      29.0      28.0
                                   Temperature      23.0      25.0      25.0
           ketamine hydrochloride  Pressure          9.0       9.0      11.0
                                   Temperature      22.0      21.0      20.0
16-10-2020 diltiazem hydrochloride Pressure         24.0       NaN      27.0
                                   Temperature      40.0       NaN      42.0
           docetaxel injection     Pressure         28.0      29.0      30.0
                                   Temperature      56.0      57.0      58.0
           ketamine hydrochloride  Pressure         16.0      17.0      18.0
                                   Temperature      13.0      14.0      15.0
17-10-2020 diltiazem hydrochloride Pressure         11.0      13.0      14.0
                                   Temperature      14.0      11.0      10.0
           docetaxel injection     Pressure         28.0      29.0      28.0
                                   Temperature      21.0      22.0      23.0
           ketamine hydrochloride  Pressure         13.0      14.0      15.0
                                   Temperature      22.0      23.0      24.0

Time                                            1:30:00  2:30:00  3:30:00  \
Date       Drug_Name               Parameter
15-10-2020 diltiazem hydrochloride Pressure        12.0     13.0      NaN
                                   Temperature     23.0     22.0      NaN
           docetaxel injection     Pressure         NaN     22.0     22.0
                                   Temperature      NaN     17.0     18.0
           ketamine hydrochloride  Pressure         8.0      NaN      NaN
                                   Temperature     24.0      NaN      NaN
16-10-2020 diltiazem hydrochloride Pressure        18.0     19.0     20.0
                                   Temperature     34.0     35.0     36.0
           docetaxel injection     Pressure        23.0     24.0      NaN
                                   Temperature     46.0     47.0      NaN
           ketamine hydrochloride  Pressure        12.0     12.0     13.0
                                   Temperature      8.0      9.0     10.0
17-10-2020 diltiazem hydrochloride Pressure         3.0      4.0      4.0
                                   Temperature     20.0     19.0     19.0
           docetaxel injection     Pressure        20.0     22.0     22.0
                                   Temperature     12.0     13.0     14.0
           ketamine hydrochloride  Pressure         8.0      9.0     10.0
                                   Temperature     13.0     14.0     15.0

Time                                            4:30:00  5:30:00  6:30:00  \
Date       Drug_Name               Parameter
15-10-2020 diltiazem hydrochloride Pressure        11.0     13.0     14.0
                                   Temperature     21.0     21.0     22.0
           docetaxel injection     Pressure         NaN     22.0     23.0
                                   Temperature      NaN     17.0     18.0
           ketamine hydrochloride  Pressure         7.0      NaN      9.0
                                   Temperature     27.0      NaN     26.0
16-10-2020 diltiazem hydrochloride Pressure        21.0     22.0     23.0
                                   Temperature     36.0     37.0     38.0
           docetaxel injection     Pressure        25.0     26.0     27.0
                                   Temperature     48.0     48.0     49.0
           ketamine hydrochloride  Pressure         NaN     15.0     15.0
                                   Temperature      NaN     11.0     12.0
17-10-2020 diltiazem hydrochloride Pressure         4.0      6.0      8.0
                                   Temperature     18.0     17.0     16.0
           docetaxel injection     Pressure        22.0     22.0     23.0
                                   Temperature     15.0     16.0     17.0
           ketamine hydrochloride  Pressure        11.0     11.0     12.0
                                   Temperature     16.0     17.0     18.0

Time                                            7:30:00  8:30:00  9:30:00
Date       Drug_Name               Parameter
15-10-2020 diltiazem hydrochloride Pressure        16.0     16.0     24.0
                                   Temperature     23.0     21.0     22.0
           docetaxel injection     Pressure         NaN      NaN     27.0
                                   Temperature      NaN      NaN     23.0
           ketamine hydrochloride  Pressure        10.0     11.0     10.0
                                   Temperature     25.0     24.0     23.0
16-10-2020 diltiazem hydrochloride Pressure        24.0     25.0     25.0
                                   Temperature     37.0     38.0     39.0
           docetaxel injection     Pressure        28.0     29.0     28.0
                                   Temperature     50.0     52.0     55.0
           ketamine hydrochloride  Pressure        15.0     15.0      NaN
                                   Temperature     12.0     11.0      NaN
17-10-2020 diltiazem hydrochloride Pressure         9.0      NaN      9.0
                                   Temperature     15.0      NaN     13.0
           docetaxel injection     Pressure        25.0     26.0     27.0
                                   Temperature     18.0     19.0     20.0
           ketamine hydrochloride  Pressure        12.0     11.0     12.0
                                   Temperature     19.0     20.0     21.0

In [121]:
pivoted_data = melted_df.pivot(index = ['Date', 'Drug_Name', 'Parameter'],
                columns = 'Time',
                values = 'Readings').reset_index()

In [122]:
pivoted_data.columns.name = None
pivoted_data.head()

,Date,Drug_Name,Parameter,10:30:00,11:30:00,12:30:00,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00
0,15-10-2020,diltiazem hydrochloride,Pressure,18.0,19.0,20.0,12.0,13.0,NaN,11.0,13.0,14.0,16.0,16.0,24.0
1,15-10-2020,diltiazem hydrochloride,Temperature,20.0,20.0,21.0,23.0,22.0,NaN,21.0,21.0,22.0,23.0,21.0,22.0
2,15-10-2020,docetaxel injection,Pressure,26.0,29.0,28.0,NaN,22.0,22.0,NaN,22.0,23.0,NaN,NaN,27.0
3,15-10-2020,docetaxel injection,Temperature,23.0,25.0,25.0,NaN,17.0,18.0,NaN,17.0,18.0,NaN,NaN,23.0
4,15-10-2020,ketamine hydrochloride,Pressure,9.0,9.0,11.0,8.0,NaN,NaN,7.0,NaN,9.0,10.0,11.0,10.0

In [123]:
  # now we will try to make our data more readable by pivoting the Parameters
data_tidy = melted_df.pivot(index = ['Date','Drug_Name', 'Time'], columns = 'Parameter', values = 'Readings').reset_index()
data_tidy.columns.name = None
data_tidy.head()

         Date                Drug_Name      Time  Pressure  Temperature
0  15-10-2020  diltiazem hydrochloride  10:30:00      18.0         20.0
1  15-10-2020  diltiazem hydrochloride  11:30:00      19.0         20.0
2  15-10-2020  diltiazem hydrochloride  12:30:00      20.0         21.0
3  15-10-2020  diltiazem hydrochloride   1:30:00      12.0         23.0
4  15-10-2020  diltiazem hydrochloride   2:30:00      13.0         22.0

In [124]:
# can we pivot with one col?
data_tidy.pivot(index = ['Drug_Name'], columns = 'Date', values = 'Temperature')

ValueError: ignored

In [125]:
data_tidy.head()

         Date                Drug_Name      Time  Pressure  Temperature
0  15-10-2020  diltiazem hydrochloride  10:30:00      18.0         20.0
1  15-10-2020  diltiazem hydrochloride  11:30:00      19.0         20.0
2  15-10-2020  diltiazem hydrochloride  12:30:00      20.0         21.0
3  15-10-2020  diltiazem hydrochloride   1:30:00      12.0         23.0
4  15-10-2020  diltiazem hydrochloride   2:30:00      13.0         22.0

In [126]:
# as we can see that the pivot function is not able to handle the duplicate values and also it does not have a way to aggregate the values.
#Therefore, we have a function called pivot_table to tackle with this
data_tidy.pivot_table(index = 'Drug_Name', columns = 'Date', values = 'Temperature', aggfunc = np.mean)

Date                     15-10-2020  16-10-2020  17-10-2020
Drug_Name
diltiazem hydrochloride   21.454545   37.454545   15.636364
docetaxel injection       20.750000   51.454545   17.500000
ketamine hydrochloride    23.555556   11.500000   18.500000

In [127]:
# for each drug we can get the average pressure and temperature for each day
data_tidy.pivot_table(index = ['Drug_Name'], columns = 'Date', values = ['Temperature','Pressure'], aggfunc = np.mean)

                          Pressure                       Temperature  \
Date                    15-10-2020 16-10-2020 17-10-2020  15-10-2020
Drug_Name
diltiazem hydrochloride  16.000000  22.545455   7.727273   21.454545
docetaxel injection      24.875000  27.000000  24.500000   20.750000
ketamine hydrochloride    9.333333  14.800000  11.500000   23.555556


Date                    16-10-2020 17-10-2020
Drug_Name
diltiazem hydrochloride  37.454545  15.636364
docetaxel injection      51.454545  17.500000
ketamine hydrochloride   11.500000  18.500000

In [128]:
# Similary, we can get the min pressure and temperature for each day for each drug
data_tidy.pivot_table(index = ['Drug_Name'], columns = 'Date', values = ['Temperature','Pressure'], aggfunc = np.min)

                          Pressure                       Temperature  \
Date                    15-10-2020 16-10-2020 17-10-2020  15-10-2020
Drug_Name
diltiazem hydrochloride       11.0       18.0        3.0        20.0
docetaxel injection           22.0       23.0       20.0        17.0
ketamine hydrochloride         7.0       12.0        8.0        20.0


Date                    16-10-2020 17-10-2020
Drug_Name
diltiazem hydrochloride       34.0       10.0
docetaxel injection           46.0       12.0
ketamine hydrochloride         8.0       13.0

## Dealing with the missing values

In [129]:
type(np.NaN)

float

In [130]:
type(None)

NoneType

In [131]:
#BasicallY string can hold anything Null, None, np.NaN but the np.Nan will always be numerical type

In [132]:
# let's check for the missing data in our dataset
df.isnull().sum()

Date         0
Drug_Name    0
Parameter    0
1:30:00      2
2:30:00      2
3:30:00      6
4:30:00      4
5:30:00      2
6:30:00      0
7:30:00      2
8:30:00      4
9:30:00      2
10:30:00     0
11:30:00     2
12:30:00     0
dtype: int64

In [133]:
df.isnull().sum(axis = 1)

0     1
1     1
2     4
3     4
4     3
5     3
6     1
7     1
8     1
9     1
10    2
11    2
12    1
13    1
14    0
15    0
16    0
17    0
dtype: int64

### Dropping the null values - let's see if it is a viable optiion or not

In [134]:
df.dropna()
# and as we can see that droping the null values vanished more that the half of the dataset

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
14,17-10-2020,docetaxel injection,Temperature,12.0,13.0,14.0,15.0,16.0,17,18.0,19.0,20.0,21,22.0,23
15,17-10-2020,docetaxel injection,Pressure,20.0,22.0,22.0,22.0,22.0,23,25.0,26.0,27.0,28,29.0,28
16,17-10-2020,ketamine hydrochloride,Temperature,13.0,14.0,15.0,16.0,17.0,18,19.0,20.0,21.0,22,23.0,24
17,17-10-2020,ketamine hydrochloride,Pressure,8.0,9.0,10.0,11.0,11.0,12,12.0,11.0,12.0,13,14.0,15

In [135]:
# thresh mentions that we want rows where at least 14 attributes are not null
df.dropna(thresh=14).shape

(12, 15)

In [136]:
df.dropna(axis = 1)
# same issue is happening if we are dropping the column having null values. Here, we cannot do any analysis with only 3 columns of readings

,Date,Drug_Name,Parameter,6:30:00,10:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,22,20,21
1,15-10-2020,diltiazem hydrochloride,Pressure,14,18,20
2,15-10-2020,docetaxel injection,Temperature,18,23,25
3,15-10-2020,docetaxel injection,Pressure,23,26,28
4,15-10-2020,ketamine hydrochloride,Temperature,26,22,20
5,15-10-2020,ketamine hydrochloride,Pressure,9,9,11
6,16-10-2020,diltiazem hydrochloride,Temperature,38,40,42
7,16-10-2020,diltiazem hydrochloride,Pressure,23,24,27
8,16-10-2020,docetaxel injection,Temperature,49,56,58
9,16-10-2020,docetaxel injection,Pressure,27,28,30
10,16-10-2020,ketamine hydrochloride,Temperature,12,13,15
11,16-10-2020,ketamine hydrochloride,Pressure,15,16,18
12,17-10-2020,diltiazem hydrochloride,Temperature,16,14,10
13,17-10-2020,diltiazem hydrochloride,Pressure,8,11,14
14,17-10-2020,docetaxel injection,Temperature,17,21,23
15,17-10-2020,docetaxel injection,Pressure,23,28,28
16,17-10-2020,ketamine hydrochloride,Temperature,18,22,24
17,17-10-2020,ketamine hydrochloride,Pressure,12,13,15

# Filling the null values

In [137]:
df['2:30:00']

0     22.0
1     13.0
2     17.0
3     22.0
4      NaN
5      NaN
6     35.0
7     19.0
8     47.0
9     24.0
10     9.0
11    12.0
12    19.0
13     4.0
14    13.0
15    22.0
16    14.0
17     9.0
Name: 2:30:00, dtype: float64

In [138]:
# As we can see that our column has 2 null entries at row 4 and 5.
# To fill the null values, we have a function called df.fillna().
# Here, in the argumenr we can pass the value we want to fill our null values with

In [139]:
# let's try to fill the values with 0
df['2:30:00'].fillna(0)

0     22.0
1     13.0
2     17.0
3     22.0
4      0.0
5      0.0
6     35.0
7     19.0
8     47.0
9     24.0
10     9.0
11    12.0
12    19.0
13     4.0
14    13.0
15    22.0
16    14.0
17     9.0
Name: 2:30:00, dtype: float64

In [140]:
# to fill the vlaues with the mean value
df['2:30:00'].fillna(df['2:30:00'].mean())

0     22.0000
1     13.0000
2     17.0000
3     22.0000
4     18.8125
5     18.8125
6     35.0000
7     19.0000
8     47.0000
9     24.0000
10     9.0000
11    12.0000
12    19.0000
13     4.0000
14    13.0000
15    22.0000
16    14.0000
17     9.0000
Name: 2:30:00, dtype: float64

In [141]:
# We have one more way to fill the null values that is
# interpolate - what it does is to divide the difference between the non values in equal parts
df['2:30:00'].interpolate(method = 'linear')

0     22.000000
1     13.000000
2     17.000000
3     22.000000
4     26.333333
5     30.666667
6     35.000000
7     19.000000
8     47.000000
9     24.000000
10     9.000000
11    12.000000
12    19.000000
13     4.000000
14    13.000000
15    22.000000
16    14.000000
17     9.000000
Name: 2:30:00, dtype: float64

In [142]:
# now, as we have already simplified and transformed our data. Let's try to fill the null values
data_tidy.head()

         Date                Drug_Name      Time  Pressure  Temperature
0  15-10-2020  diltiazem hydrochloride  10:30:00      18.0         20.0
1  15-10-2020  diltiazem hydrochloride  11:30:00      19.0         20.0
2  15-10-2020  diltiazem hydrochloride  12:30:00      20.0         21.0
3  15-10-2020  diltiazem hydrochloride   1:30:00      12.0         23.0
4  15-10-2020  diltiazem hydrochloride   2:30:00      13.0         22.0

In [143]:
data_tidy.isnull().sum()

Date            0
Drug_Name       0
Time            0
Pressure       13
Temperature    13
dtype: int64

In [144]:
data_tidy[data_tidy['Pressure'].isnull()]

          Date                Drug_Name      Time  Pressure  Temperature
5   15-10-2020  diltiazem hydrochloride   3:30:00       NaN          NaN
15  15-10-2020      docetaxel injection   1:30:00       NaN          NaN
18  15-10-2020      docetaxel injection   4:30:00       NaN          NaN
21  15-10-2020      docetaxel injection   7:30:00       NaN          NaN
22  15-10-2020      docetaxel injection   8:30:00       NaN          NaN
28  15-10-2020   ketamine hydrochloride   2:30:00       NaN          NaN
29  15-10-2020   ketamine hydrochloride   3:30:00       NaN          NaN
31  15-10-2020   ketamine hydrochloride   5:30:00       NaN          NaN
37  16-10-2020  diltiazem hydrochloride  11:30:00       NaN          NaN
53  16-10-2020      docetaxel injection   3:30:00       NaN          NaN
66  16-10-2020   ketamine hydrochloride   4:30:00       NaN          NaN
71  16-10-2020   ketamine hydrochloride   9:30:00       NaN          NaN
82  17-10-2020  diltiazem hydrochloride   8:30:00       NaN          NaN

In [145]:
# let's create a function first to calculate the mean temprature and pressure column
def avg_values(x):
  x['Avg_temprature'] = x['Temperature'].mean()
  x['Avg_pressure'] = x['Pressure'].mean()
  return x

In [146]:
data_tidy.groupby(['Drug_Name'])[['Temperature','Pressure']].mean()

                         Temperature   Pressure
Drug_Name
diltiazem hydrochloride    24.848485  15.424242
docetaxel injection        30.387097  25.483871
ketamine hydrochloride     17.709677  11.935484

In [147]:
data_tidy = data_tidy.groupby('Drug_Name').apply(avg_values)

<ipython-input-147-3cdd0ccb6e9e>:1: FutureWarning: Not prepending group keys to the result index of transform-like apply. In the future, the group keys will be included in the index, regardless of whether the applied function returns a like-indexed object.
To preserve the previous behavior, use

	>>> .groupby(..., group_keys=False)

To adopt the future behavior and silence this warning, use

	>>> .groupby(..., group_keys=True)
  data_tidy = data_tidy.groupby('Drug_Name').apply(avg_values)

In [148]:
# now, as we have extracted the average values, we will fill our null values with them
data_tidy['Temperature'].fillna(data_tidy['Avg_temprature'], inplace = True)
data_tidy['Pressure'].fillna(data_tidy['Avg_pressure'], inplace = True)

In [149]:
data_tidy.isnull().sum()

Date              0
Drug_Name         0
Time              0
Pressure          0
Temperature       0
Avg_temprature    0
Avg_pressure      0
dtype: int64

In [150]:
data_tidy.loc[[5,15,21,28]]
# Voila! we got our null values filled without any loss of data

,Date,Drug_Name,Time,Pressure,Temperature,Avg_temprature,Avg_pressure
5,15-10-2020,diltiazem hydrochloride,3:30:00,15.424242,24.848485,24.848485,15.424242
15,15-10-2020,docetaxel injection,1:30:00,25.483871,30.387097,30.387097,25.483871
21,15-10-2020,docetaxel injection,7:30:00,25.483871,30.387097,30.387097,25.483871
28,15-10-2020,ketamine hydrochloride,2:30:00,11.935484,17.709677,17.709677,11.935484

# PD.cut

In [151]:
# We can use this functinality to categorize our NUMERICAL data
# for example - categorizing the temperature in low, med high

In [152]:
# Let's see the range of our temperature data before creating the bins
print(data_tidy['Temperature'].min(), data_tidy['Temperature'].max())

8.0 58.0

In [153]:
temp_points = [5,20,35,50,60]   # this will work as our bin i.e. 8-20, 20-35, 35-50, 50-60
temp_lables = ['low','med','high','very_high']

data_tidy['temp_cat'] = pd.cut(data_tidy['Temperature'], bins=temp_points, labels = temp_lables)

In [154]:
data_tidy.head()

,Date,Drug_Name,Time,Pressure,Temperature,Avg_temprature,Avg_pressure,temp_cat
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0,24.848485,15.424242,low
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0,24.848485,15.424242,low
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0,24.848485,15.424242,med
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0,24.848485,15.424242,med
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0,24.848485,15.424242,med

In [155]:
data_tidy['temp_cat'].value_counts()

low          50
med          38
high         15
very_high     5
Name: temp_cat, dtype: int64

## String functions on Pandas series

In [156]:
# we will have to typecast the column to string by using .str before applying any string functions
# for example, we want only the rows where drug name is like %chloride%
data_tidy.loc[data_tidy['Drug_Name'].str.contains('chloride')]

,Date,Drug_Name,Time,Pressure,Temperature,Avg_temprature,Avg_pressure,temp_cat
0,15-10-2020,diltiazem hydrochloride,10:30:00,18.0,20.0,24.848485,15.424242,low
1,15-10-2020,diltiazem hydrochloride,11:30:00,19.0,20.0,24.848485,15.424242,low
2,15-10-2020,diltiazem hydrochloride,12:30:00,20.0,21.0,24.848485,15.424242,med
3,15-10-2020,diltiazem hydrochloride,1:30:00,12.0,23.0,24.848485,15.424242,med
4,15-10-2020,diltiazem hydrochloride,2:30:00,13.0,22.0,24.848485,15.424242,med
...,...,...,...,...,...,...,...,...
103,17-10-2020,ketamine hydrochloride,5:30:00,11.0,17.0,17.709677,11.935484,low
104,17-10-2020,ketamine hydrochloride,6:30:00,12.0,18.0,17.709677,11.935484,low
105,17-10-2020,ketamine hydrochloride,7:30:00,12.0,19.0,17.709677,11.935484,low
106,17-10-2020,ketamine hydrochloride,8:30:00,11.0,20.0,17.709677,11.935484,low
107,17-10-2020,ketamine hydrochloride,9:30:00,12.0,21.0,17.709677,11.935484,med

In [157]:
data_tidy['Date'].str[:4]

0      15-1
1      15-1
2      15-1
3      15-1
4      15-1
       ...
103    17-1
104    17-1
105    17-1
106    17-1
107    17-1
Name: Date, Length: 108, dtype: object

In [158]:
data_tidy['Date'].str.split('-')

0      [15, 10, 2020]
1      [15, 10, 2020]
2      [15, 10, 2020]
3      [15, 10, 2020]
4      [15, 10, 2020]
            ...
103    [17, 10, 2020]
104    [17, 10, 2020]
105    [17, 10, 2020]
106    [17, 10, 2020]
107    [17, 10, 2020]
Name: Date, Length: 108, dtype: object

# Pandas Date time function

In [159]:
# to_datetime()
#data_tidy['Date'] = pd.to_datetime(data_tidy['Date'], format= "%d-%m-%y")

In [161]:
data_tidy['Timestamp'] = data_tidy['Date'] + ' ' + data_tidy['Time']

In [162]:
data_tidy.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 108 entries, 0 to 107
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Date            108 non-null    object
 1   Drug_Name       108 non-null    object
 2   Time            108 non-null    object
 3   Pressure        108 non-null    float64
 4   Temperature     108 non-null    float64
 5   Avg_temprature  108 non-null    float64
 6   Avg_pressure    108 non-null    float64
 7   temp_cat        108 non-null    category
 8   Timestamp       108 non-null    object
dtypes: category(1), float64(4), object(4)
memory usage: 12.0+ KB

In [164]:
data_tidy['Timestamp'] = pd.to_datetime(data_tidy['Timestamp'])

In [166]:
data_tidy['Timestamp'].dt.year

0      2020
1      2020
2      2020
3      2020
4      2020
       ...
103    2020
104    2020
105    2020
106    2020
107    2020
Name: Timestamp, Length: 108, dtype: int64

In [167]:
# now, to save our dataset till yet we can use
data_tidy.to_csv('Pharma_tidy')